"""Simpro API Client: reusable integration layer for the Simpro REST API."""

from simpro_client.client import SimproClient
from simpro_client.config import SimproSettings, get_settings
from simpro_client.endpoints import Page
from simpro_client.models import (
    AddressBlock,
    Asset,
    Attachment,
    Company,
    CompanyAddress,
    CompanyCustomer,
    Contact,
    ContactRef,
    ContractRef,
    Currency,
    CustomerContactRef,
    CustomerProfile,
    CustomerRef,
    CustomerSummary,
    CustomFieldDefinition,
    CustomFieldValue,
    Employee,
    EmployeeContact,
    IndividualCustomer,
    Job,
    JobNote,
    NamedRef,
    NoteAttachment,
    NoteReference,
    NoteVisibility,
    PreferredTechnician,
    ProjectStatusCode,
    Quote,
    Site,
    SiteBillingAddress,
    SitePrimaryContact,
    StaffRef,
)

__all__ = [
    "AddressBlock",
    "Asset",
    "Attachment",
    "Company",
    "CompanyAddress",
    "CompanyCustomer",
    "Contact",
    "ContactRef",
    "ContractRef",
    "Currency",
    "CustomFieldDefinition",
    "CustomFieldValue",
    "CustomerContactRef",
    "CustomerProfile",
    "CustomerRef",
    "CustomerSummary",
    "Employee",
    "EmployeeContact",
    "IndividualCustomer",
    "Job",
    "JobNote",
    "NamedRef",
    "NoteAttachment",
    "NoteReference",
    "NoteVisibility",
    "Page",
    "PreferredTechnician",
    "ProjectStatusCode",
    "Quote",
    "SimproClient",
    "SimproSettings",
    "Site",
    "SiteBillingAddress",
    "SitePrimaryContact",
    "StaffRef",
    "get_settings",
]
__version__ = "0.1.0"
